# 서버 포트 및 CORS 설정
server:
  port: 8080

spring:
  # H2 콘솔 설정
  h2:
    console:
      enabled: true
      path: /h2-console

  # Datasource 설정
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true